<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>LeadGreen — {{ config('app.name') }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; font-size: 14px; color: #263238; background: #f5f5f5; padding: 40px 20px; }
        .container { max-width: 1100px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
        .header { background: #0E90D9; color: #fff; padding: 24px 32px; }
        .header h1 { font-size: 20px; }
        .header p { font-size: 13px; opacity: .9; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; }
        th { text-align: left; padding: 12px 16px; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: #6b7280; background: #f9fafb; border-bottom: 2px solid #0E90D9; }
        td { padding: 12px 16px; border-bottom: 1px solid #e5e7eb; }
        .empty { padding: 60px 32px; text-align: center; color: #6b7280; }
        .footer { padding: 16px 32px; text-align: center; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>LeadGreen — {{ $total }} {{ Str::plural('prospect', $total) }}</h1>
            <p>Exported {{ $exportedAt }}</p>
        </div>

        @if ($total > 0)
            <table>
                <thead>
                    <tr>
                        <th>ID</th><th>Nome</th><th>Telefone</th><th>Cidade</th><th>Estado</th><th>Tipos</th><th>Avaliação</th><th>Reviews</th><th>Website</th><th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {!! $rows !!}
                </tbody>
            </table>
        @else
            <div class="empty">No prospects match the selected filters.</div>
        @endif

        <div class="footer">Generated by {{ config('app.name') }}</div>
    </div>
</body>
</html>
